version: '3.4'

services:
  mqttserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44337
      - 'Kestrel:Certificates:Default:Password=mqttpsw'
      - 'Kestrel:Certificates:Default:Path=/root/.aspnet/https/MQTTExample.pfx'
    ports:
      - "53692:80"
      - "44337:443"
      - "1883:1883"
    volumes:
      - ./ssl/:/root/.aspnet/https/
    